name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip from src
        run: |
          cd src
          zip -r ../survivors-mod.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: survivors-mod.zip

      - name: Upload to mod.io
        uses: nickelc/upload-to-modio@v3.0.0
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: 16
          mod: 4791538
          path: survivors-mod.zip
          version: ${{ github.ref_name }}
          changelog: GitHub release ${{ github.ref_name }}
          active: true
